name: Build and test
on: [push, pull_request]

env:
  GO_VERSION: "1.24"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Go
        run: go build -v ./...

      - name: Test Go
        run: go test -v ./...

      - name: Lint Go
        run: go vet ./...
